### ISSUE TITLE
"Invalid Credentials" despite having set my username/password

### ISSUE THREAD

**Issue by CrimsonCuttle** [scottmconway/shopgoodwill-scripts#27]
Getting the following error when trying to run bid_sniper.py:
`Traceback (most recent call last):
  File "E:\Programs\shopgoodwill-scripts-main\bid_sniper.py", line 495, in <module>
    main()
  File "E:\Programs\shopgoodwill-scripts-main\bid_sniper.py", line 487, in main
    bid_sniper = BidSniper(config, args.dry_run)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Programs\shopgoodwill-scripts-main\bid_sniper.py", line 134, in __init__
    self.shopgoodwill_client = shopgoodwill.Shopgoodwill(config["auth_info"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Programs\shopgoodwill-scripts-main\shopgoodwill.py", line 79, in __init__
    self.login(
  File "E:\Programs\shopgoodwill-scripts-main\shopgoodwill.py", line 214, in login
    raise Exception("Invalid credentials")
Exception: Invalid credentials`
Despite having put my username/password into the config.json. Why?

**Comment by CrimsonCuttle** [comment]
Nevermind. I had to delete the empty fields entirely (not just leave them empty), as that was confusing the program.
